language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

arch:
  - amd64
  - ppc64le
  
install:
  - pip install .

script:
  - python setup.py --version  # Detect encoding problems
  - python -m pytest

env:
  global:
    - TWINE_USERNAME=marcelm

jobs:
  include:
    - stage: deploy
      services:
        - docker
      python: "3.6"
      install: python3 -m pip install Cython setuptools_scm twine
      if: tag IS present
      script:
        - |
          python3 setup.py sdist &&
          ./buildwheels.sh &&
          ls -l dist/ &&
          python3 -m twine upload dist/*

  allowed_failures:
    - python: "nightly"
